### ISSUE TITLE
Corrupt workspace.zip

### ISSUE THREAD

**Issue by ignapas** [ITISFoundation/osparc-issues#719] opened 2022-09-15 17:30 UTC
[OEC:140172296695424]
Logs: https://monitoring.osparc.speag.com/graylog/messages/graylog_134/b25ae7f1-3519-11ed-b190-0242ac130011

_Issue created from a [Mattermost message](https://mattermost.speag.com:443/_redirect/pl/bstc7t3sh3d558bdataubprimc) *by `@msteiner`*._

**Comment by ignapas** [comment] 2022-09-15 17:33
@mrnicegyu11 This is what I texted you about yesterday in the evening. ``workspace.zip`` in database is corrupt. is there a way to restore last working version?

**Comment by pcrespov** [comment] 2022-09-15 17:45
@GitHK see below the relevant (safe) part of the logs referred above:
```log
ERROR:simcore_service_director_v2.modules.dynamic_sidecar.scheduler.task:Observation of service_name='dy-sidecar_9bd81e40-3456-4c2c-a9d7-e796c91f92b3'  unexpectedly failed [OEC:140172296695424]

...

servicelib.long_running_tasks._errors.TaskClientResultError: Task simcore_service_dynamic_sidecar.modules.long_running_tasks.task_restore_state.1f015496-90eb-438f-b620-0192af1a1283 finished with exception: 'File is not a zip file'
  File "/home/scu/.venv/lib/python3.9/site-packages/servicelib/long_running_tasks/_task.py", line 409, in _progress_task
    return await handler(progress, **task_kwargs)

  File "/home/scu/.venv/lib/python3.9/site-packages/simcore_service_dynamic_sidecar/modules/long_running_tasks.py", line 172, in task_restore_state
    await logged_gather(

  File "/home/scu/.venv/lib/python3.9/site-packages/servicelib/utils.py", line 134, in logged_gather
    raise error

  File "/home/scu/.venv/lib/python3.9/site-packages/servicelib/utils.py", line 113, in sem_task
    return await task

  File "/home/scu/.venv/lib/python3.9/site-packages/simcore_sdk/node_data/data_manager.py", line 170, in pull
    await unarchive_dir(

  File "/home/scu/.venv/lib/python3.9/site-packages/servicelib/archiving_utils.py", line 159, in unarchive_dir
    with zipfile.ZipFile(

  File "/usr/local/lib/python3.9/zipfile.py", line 1266, in __init__
    self._RealGetContents()

  File "/usr/local/lib/python3.9/zipfile.py", line 1333, in _RealGetContents
    raise BadZipFile("File is not a zip file")
```

The problem is clearly that somehow the zipping of workspace was wrong and some invalid file was uploaded. 
I wonder if we could add a step to validate the final zip before uploading... 

Notice that this is da;co and not AWS, so the multipart upload does not apply!
I will add this a part of the issues of the sidecar to review.

**Comment by pcrespov** [comment] 2022-09-16 09:22
@mrnicegyu11 would you please assist to restore the workspace from the backup? If you have any questions, please contact me

**Comment by sanderegg** [comment] 2023-02-28 07:22
@GitHK are you going to do something with this one? or we close. this dates way back

**Comment by GitHK** [comment] 2023-02-28 07:24
Will not do anything here. Did not hear any more reports about it. I think we already had a few fixes addressing zip files since then.
Closing for now

**Closed by GitHK** 2023-02-28 07:24 UTC
Labels: type:bug, Feedback
