### ISSUE TITLE
large output files don't unzip in input port 

### ISSUE THREAD

**Issue by newton1985** [ITISFoundation/osparc-issues#550] opened 2021-10-11 13:27 UTC
## Long story short
When connecting a large output from one node to the next, the file is not unzipped in the input port (but I can unzip manually). Upstream and downstream services are jupyterlab smash nbs, v2.5.5, on production. Also, the icon in "Settings" at the top resolves to an "x" instead of a checkmark.

## Expected behaviour
I expect the files to be automatically unzipped in the input port.

## Actual behaviour
Files are not unzipped.

## Steps to reproduce
Map a large output in one node to an input port in another.

Note: your environment was attached but will not be displayed
<!--
## Your environment
```json
[
  {
    "name": "osparc-simcore",
    "version": "c00770d",
    "url": "https://github.com/ITISFoundation/osparc-simcore/tree/c00770d/"
  },
  {
    "name": "osparc-simcore UI [clean]",
    "version": "c00770d",
    "url": "https://github.com/ITISFoundation/osparc-simcore/tree/c00770d/services/web/client/"
  },
  {
    "name": "qooxdoo-compiler",
    "version": "1.0.0-beta.20200111-0015",
    "url": "https://github.com/qooxdoo/qooxdoo-compiler"
  },
  {
    "name": "osparc",
    "version": "1.0.0",
    "url": ""
  },
  {
    "name": "qooxdoo framework",
    "version": "6.0.0-beta-20200110-0942",
    "url": "http://qooxdoo.org"
  },
  {
    "name": "qx-iconfont-fontawesome5",
    "version": "0.2.0",
    "url": "https://github.com/ITISFoundation/qx-iconfont-fontawesome5"
  },
  {
    "name": "qx-iconfont-material",
    "version": "0.1.7",
    "url": "https://github.com/ITISFoundation/qx-osparc-theme"
  },
  {
    "name": "qx-osparc-theme",
    "version": "0.5.6",
    "url": "https://github.com/ITISFoundation/qx-osparc-theme"
  },
  {
    "name": "socket.io",
    "version": "2.2.0",
    "url": "https://github.com/socketio/socket.io"
  },
  {
    "name": "svg.js",
    "version": "2.7.1",
    "url": "https://github.com/svgdotjs/svg.js"
  },
  {
    "name": "jsondiffpatch",
    "version": "0.3.11",
    "url": "https://github.com/benjamine/jsondiffpatch"
  },
  {
    "name": "jsonTreeViewer",
    "version": "0.6.0",
    "url": "https://github.com/summerstyle/jsonTreeViewer"
  },
  {
    "name": "DOMPurify",
    "version": "2.0.0",
    "url": "https://github.com/cure53/DOMPurify"
  },
  {
    "screenResolution": {
      "width": 2560,
      "height": 1440
    },
    "windowResolution": {
      "width": 2560,
      "height": 1297
    }
  }
]
```

**Comment by KZzizzle** [comment] 2021-12-15 12:57
duplicate of #499 : closing

**Closed by KZzizzle** 2021-12-15 12:57 UTC
Labels: Feedback
