### ISSUE TITLE
Sidecar cannot reach storage

### ISSUE THREAD

**Issue by bisgaard-itis** [ITISFoundation/osparc-issues#1264] opened 2024-02-12 13:25 UTC
~Placeholder for https://z43.manuscript.com/f/cases/191098/service-failed-sidecar-cannot-reach-storage~

**Comment by matusdrobuliak66** [comment] 2024-02-20 07:43
https://git.speag.com/oSparc/osparc-infra/-/issues/incident/47

**Comment by YuryHrytsuk** [comment] 2024-02-21 09:20
On the surface, it is a DNS problem. Some of the potential DNS issues are described below

As best I can tell, there are situations where stopping a container on an attachable overlay network doesn't propagate the change the other nodes in the swarm.

**Comment by YuryHrytsuk** [comment] 2024-02-29 10:00
The fix is merged. We will observe it for a couple of days before closing

**Comment by GitHK** [comment] 2024-02-29 13:19
@sanderegg I'll drop a refenrece to the issue in one of my PRs

**Comment by YuryHrytsuk** [comment] 2024-02-29 16:00
> Just a remark on this "fix":
> 
>     * spaghetti code: Dynamic-sidecar --> storage uses https,
> 
>     * all other services use regular http
>       As much as I understand the need for this fix I think the solution is half backed and will only increase code complexity and understanding.
> 
> 
> I would be more than happy that at least references to this issue are set in the osparc-simcore code because otherwise it makes no sense. @GitHK @YuryHrytsuk

This is true. The fix doesn't seem to be the best solution. On the other hand I don't see any other solution to the problem. And the main issue is that we still don't fully understand the root of the problem (also because it is not easy to reproduce).

I don't feel that any of us will dive deep into docker for a couple of days (or a week) to find out the root cause.

Any proposals how to get away from current position?

@sanderegg @GitHK @mrnicegyu11

**Comment by YuryHrytsuk** [comment] 2024-03-11 08:15
After this solution was introduced to master deployment, storage failures never occurred. I consider this issue to be fixed as of now

**Closed by YuryHrytsuk** 2024-03-11 08:15 UTC
