### ISSUE TITLE
Jupyter node files ownership

### ISSUE THREAD

**Issue by nitrosx** [ITISFoundation/osparc-issues#352] opened 2020-10-06 15:29 UTC
#### Long story short
When I open a terminal in a jupyter lab node, and I list the files, I see that files are owned by user jovyan and group users.
![jupyterlab_terminal_user_ownership](https://user-images.githubusercontent.com/2193724/95223006-18bf2b00-07c7-11eb-8627-56f84b5b195d.png)

## Expected behaviour
I would suggest to make sure that a generic user is created in the container, and all the jupyter files are owned by this generic user

## Actual behaviour
Jupyter files are owned by user jovyan.

## Steps to reproduce
In the dashboard add a "Jupyter Octave+Python Math" node, access the jupyter interface. Start a terminal from the launcher and run the command "ls -l".
The files are owned by user jovyan.
Please check attached image.

Note: your environment was attached but will not be displayed
<!--
## Your environment
```json
[
  {
    "name": "osparc-simcore",
    "version": "c6d5236",
    "url": "https://github.com/ITISFoundation/osparc-simcore/tree/c6d5236/"
  },
  {
    "name": "osparc-simcore UI [clean]",
    "version": "c6d5236",
    "url": "https://github.com/ITISFoundation/osparc-simcore/tree/c6d5236/services/web/client/"
  },
  {
    "name": "qooxdoo-compiler",
    "version": "1.0.0-beta.20200111-0015",
    "url": "https://github.com/qooxdoo/qooxdoo-compiler"
  },
  {
    "name": "osparc",
    "version": "1.0.0",
    "url": ""
  },
  {
    "name": "qooxdoo framework",
    "version": "6.0.0-beta-20200110-0942",
    "url": "http://qooxdoo.org"
  },
  {
    "name": "qx-iconfont-fontawesome5",
    "version": "0.2.0",
    "url": "https://github.com/ITISFoundation/qx-iconfont-fontawesome5"
  },
  {
    "name": "qx-iconfont-material",
    "version": "0.1.7",
    "url": "https://github.com/ITISFoundation/qx-osparc-theme"
  },
  {
    "name": "qx-osparc-theme",
    "version": "0.5.6",
    "url": "https://github.com/ITISFoundation/qx-osparc-theme"
  },
  {
    "name": "socket.io",
    "version": "2.2.0",
    "url": "https://github.com/socketio/socket.io"
  },
  {
    "name": "jsondiffpatch",
    "version": "0.3.11",
    "url": "https://github.com/benjamine/jsondiffpatch"
  },
  {
    "name": "jsonTreeViewer",
    "version": "0.6.0",
    "url": "https://github.com/summerstyle/jsonTreeViewer"
  },
  {
    "name": "DOMPurify",
    "version": "2.0.0",
    "url": "https://github.com/cure53/DOMPurify"
  },
  {
    "name": "svg.js",
    "version": "2.7.1",
    "url": "https://github.com/svgdotjs/svg.js"
  },
  {
    "screenResolution": {
      "width": 2560,
      "height": 1440
    },
    "windowResolution": {
      "width": 2560,
      "height": 1340
    }
  }
]
```

**Comment by KZzizzle** [comment] 2021-12-15 10:37
duplicate of #351

**Closed by KZzizzle** 2021-12-15 10:37 UTC
