### ISSUE TITLE
When working in the same notebook, variables are not persistent between the octave and python kernel, although I can switch between them from one cell to the next.

### ISSUE THREAD

**Issue by nitrosx** [ITISFoundation/osparc-issues#301] opened 2020-09-03 20:15 UTC
When working in the same notebook, variables are not persistent between the octave and python kernel, although I can switch between them from one cell to the next.
If this is the intended behaviour, it should be clearly communicated to the user.

_Originally posted by @nitrosx in https://github.com/ITISFoundation/osparc-issues/issues/267#issuecomment-668598888_

**Comment by nitrosx** [comment] 2020-09-03 20:19
Possible solutions:
1. disable multiple kernels within the same jupyter notebook
2. split in 2 different services: one for jupyter lab with python and one with jupyter lab with octave.(not preferred)
3. if the user changes the kernel on a specific cell within the same jupyter notebook, a pop up shows up indicating that variables are not shared across different kernels

**Comment by KZzizzle** [comment] 2020-09-06 20:43
@pcrespov - is it possible to create custom popups or any other alerts with Jupyterlab?

**Comment by KZzizzle** [comment] 2020-09-06 20:44
@nitrosx out of curiosity, what is your use case for passing variables between the two kernels?

**Comment by elisabettai** [comment] 2022-06-14 09:15
Hi @pcrespov, I assigned to you since you may know if that's possible. Do you think is it?

**Comment by pcrespov** [comment] 2022-06-16 12:51
>@pcrespov - is it possible to create custom popups or any other alerts with Jupyterlab?

It seems popups were removed https://github.com/ipython/ipython/pull/7341

**Comment by pcrespov** [comment] 2022-06-16 13:08
> When working in the same notebook, variables are not persistent between the octave and python kernel, although I can switch between them from one cell to the next. If this is the intended behaviour, it should be clearly communicated to the user.
> 
> _Originally posted by @nitrosx in [#267 (comment)](https://github.com/ITISFoundation/osparc-issues/issues/267#issuecomment-668598888)_

@nitrosx IMO this would be the expected behavior since each cell is communicating with a different kernel (*) which in addition has a different language interpreter (i.e. octave or python resp.).

(*) essentially a kernel is a separate process that runs an interpreter (e.g. python, octave, mathematica, ...) and receives the "text" commands that you have in your cell.

Nonetheless, there are some similar cases that can be handled out of the box. For instance, interaction between python kernel and associated shell (commands with ``!``) can be done in a single cell and can move variables from one to the other. This is a cell that does that
```python
# Install a pip package in the current Jupyter kernel
import sys
!{sys.executable} -m pip install numpy
```
Taken from [installing-python-packages-from-jupyter](https://jakevdp.github.io/blog/2017/12/05/installing-python-packages-from-jupyter/#How-to-use-Pip-from-the-Jupyter-Notebook)


The way to achieve "inter-kernel communication" would be instructing it via magic commands (the ones starting with ``%``) . I have read about multikernel approaches before, for instance https://vatlab.github.io/blog/post/sos-notebook but IMO this increases the complexity and one needs to be careful to account whether that is worth. A similar scenario happens with language binders used to connect code in different languages. The additional complexity here is that this "pieces of code" run in different processes.

**Comment by pcrespov** [comment] 2022-06-16 13:17
> Possible solutions:
> 
> 1. disable multiple kernels within the same jupyter notebook
> 2. split in 2 different services: one for jupyter lab with python and one with jupyter lab with octave.(not preferred)
> 3. if the user changes the kernel on a specific cell within the same jupyter notebook, a pop up shows up indicating that variables are not shared across different kernels


1. yes, but i think it is a bit drastic measure since sometimes it is handy to use some independent snippet in different languages. Not all cells must always  interact between each other ,right? 
2.This division is already in place by having different kernels. E.g. jupyter-math has separate octave and python kernels. The fact that you can write python in the octave is because is simply because is the natural language for notebooks. BUT you will not be able to write octave if you start the python kernel
3. I mention something above

**Comment by elisabettai** [comment] 2022-10-19 08:02
This has been solved with a note in the readme of the jupyterlab services (see [#9](https://github.com/ITISFoundation/jupyter-math/pull/9))

**Closed by elisabettai** 2022-10-19 08:02 UTC
Labels: Feedback
