### ISSUE TITLE
hovering cursor with interactive viewer grabs rotation without click

### ISSUE THREAD

**Issue by newton1985** [ITISFoundation/osparc-issues#500] opened 2021-08-30 11:40 UTC
## Long story short
For interactive views in a jupyter smash service, hovering the cursor over the window automatically grabs the rotation function and doesn't let go (i.e., even without clicking the mouse). This makes it extremely difficult to manipulate scenes.

## Expected behaviour
I expect the rotation to activate only during left-click and hold.

## Actual behaviour
Rotation is grabbed anytime the mouse hovers over the viewing window.

## Steps to reproduce
Chrome browser on windows PC.

Note: your environment was attached but will not be displayed
<!--
## Your environment
```json
[
  {
    "name": "osparc-simcore",
    "version": "3299ea6",
    "url": "https://github.com/ITISFoundation/osparc-simcore/tree/3299ea6/"
  },
  {
    "name": "osparc-simcore UI [clean]",
    "version": "3299ea6",
    "url": "https://github.com/ITISFoundation/osparc-simcore/tree/3299ea6/services/web/client/"
  },
  {
    "name": "qooxdoo-compiler",
    "version": "1.0.0-beta.20200111-0015",
    "url": "https://github.com/qooxdoo/qooxdoo-compiler"
  },
  {
    "name": "osparc",
    "version": "1.0.0",
    "url": ""
  },
  {
    "name": "qooxdoo framework",
    "version": "6.0.0-beta-20200110-0942",
    "url": "http://qooxdoo.org"
  },
  {
    "name": "qx-iconfont-fontawesome5",
    "version": "0.2.0",
    "url": "https://github.com/ITISFoundation/qx-iconfont-fontawesome5"
  },
  {
    "name": "qx-iconfont-material",
    "version": "0.1.7",
    "url": "https://github.com/ITISFoundation/qx-osparc-theme"
  },
  {
    "name": "qx-osparc-theme",
    "version": "0.5.6",
    "url": "https://github.com/ITISFoundation/qx-osparc-theme"
  },
  {
    "name": "socket.io",
    "version": "2.2.0",
    "url": "https://github.com/socketio/socket.io"
  },
  {
    "name": "svg.js",
    "version": "2.7.1",
    "url": "https://github.com/svgdotjs/svg.js"
  },
  {
    "name": "jsondiffpatch",
    "version": "0.3.11",
    "url": "https://github.com/benjamine/jsondiffpatch"
  },
  {
    "name": "jsonTreeViewer",
    "version": "0.6.0",
    "url": "https://github.com/summerstyle/jsonTreeViewer"
  },
  {
    "name": "DOMPurify",
    "version": "2.0.0",
    "url": "https://github.com/cure53/DOMPurify"
  },
  {
    "screenResolution": {
      "width": 2560,
      "height": 1440
    },
    "windowResolution": {
      "width": 2560,
      "height": 1240
    }
  }
]
```

**Comment by KZzizzle** [comment] 2021-12-15 12:35
duplicate of #548 - closing

**Closed by KZzizzle** 2021-12-15 12:35 UTC
Labels: Feedback
