### ISSUE TITLE
Jupyterlab / Interactive Services Should Accept > 1 Input

### ISSUE THREAD

**Issue by newton1985** [ITISFoundation/osparc-issues#373] opened 2020-11-10 16:09 UTC
## Long story short
Interactive (e.g. jupyter lab) services currently only accept one input. This is quite limiting in terms of implementing more advanced workflows; often a service needs to accept data streams from two different sources in order to integrate/compare them.

## Requested behavior
Interactive services accept >1 (ideally N, where N is an arbitrary integer >= 1) inputs.

Note: your environment was attached but will not be displayed
<!--
## Your environment
```json
[
  {
    "name": "osparc-simcore",
    "version": "900830d",
    "url": "https://github.com/ITISFoundation/osparc-simcore/tree/900830d/"
  },
  {
    "name": "osparc-simcore UI [clean]",
    "version": "900830d",
    "url": "https://github.com/ITISFoundation/osparc-simcore/tree/900830d/services/web/client/"
  },
  {
    "name": "qooxdoo-compiler",
    "version": "1.0.0-beta.20200111-0015",
    "url": "https://github.com/qooxdoo/qooxdoo-compiler"
  },
  {
    "name": "osparc",
    "version": "1.0.0",
    "url": ""
  },
  {
    "name": "qooxdoo framework",
    "version": "6.0.0-beta-20200110-0942",
    "url": "http://qooxdoo.org"
  },
  {
    "name": "qx-iconfont-fontawesome5",
    "version": "0.2.0",
    "url": "https://github.com/ITISFoundation/qx-iconfont-fontawesome5"
  },
  {
    "name": "qx-iconfont-material",
    "version": "0.1.7",
    "url": "https://github.com/ITISFoundation/qx-osparc-theme"
  },
  {
    "name": "qx-osparc-theme",
    "version": "0.5.6",
    "url": "https://github.com/ITISFoundation/qx-osparc-theme"
  },
  {
    "name": "socket.io",
    "version": "2.2.0",
    "url": "https://github.com/socketio/socket.io"
  },
  {
    "name": "jsondiffpatch",
    "version": "0.3.11",
    "url": "https://github.com/benjamine/jsondiffpatch"
  },
  {
    "name": "jsonTreeViewer",
    "version": "0.6.0",
    "url": "https://github.com/summerstyle/jsonTreeViewer"
  },
  {
    "name": "DOMPurify",
    "version": "2.0.0",
    "url": "https://github.com/cure53/DOMPurify"
  },
  {
    "name": "svg.js",
    "version": "2.7.1",
    "url": "https://github.com/svgdotjs/svg.js"
  },
  {
    "screenResolution": {
      "width": 2560,
      "height": 1440
    },
    "windowResolution": {
      "width": 1704,
      "height": 868
    }
  }
]
```

**Comment by newton1985** [comment] 2020-11-10 16:10
<img width="377" alt="Screenshot 2020-11-10 164238" src="https://user-images.githubusercontent.com/70750341/98699547-8dadf380-2377-11eb-967c-33df01e7e261.png">

**Comment by KZzizzle** [comment] 2021-12-15 10:40
duplicate of #299

**Closed by KZzizzle** 2021-12-15 10:40 UTC
Labels: Feedback
