### ISSUE TITLE
Users notify users

### ISSUE THREAD

**Issue by esraneufeld** [ITISFoundation/osparc-issues#917] opened 2023-04-04 12:33 UTC
A user can add a note to the workbench, similarly to how a text field or frame can now be added.
when writing in that note, it is possible to address another user by typing @username, where _username_ needs to be part of the same organization. if _username_ already has access to the study, he will receive a notification that contains the note. if not, the user gets asked whether _username_ the study should be shared with _username_. if the answer is yes, the study is shared and _username_ receives the notification, including the note.
the notification should contain a way of opening the study, at least, if the user accesses the notification while being on the landing page.
```[tasklist]
### Watermelon
- [ ] Sticky Notes
```

**Comment by pcrespov** [comment] 2023-04-07 15:24
## Goal for sprint [Jelly Beans](https://github.com/ITISFoundation/osparc-issues/milestone/41)
- ...
- ...

**Comment by elisabettai** [comment] 2023-10-13 14:00
Closing this one. It is a duplicate of https://github.com/ITISFoundation/osparc-issues/issues/1096 and that one has been closed (for NIH at least)

**Closed by elisabettai** 2023-10-13 14:00 UTC
Labels: PO issue
