### ISSUE TITLE
Expose Progress of Simulation/Computation (Sim4Life's iSolve) to Users

### ISSUE THREAD

**Issue by AntoninoMarioC** [ITISFoundation/osparc-issues#562] opened 2021-11-17 08:17 UTC
## Long story short
There is no information about the progress of some work, e.g. the status of solvers. This information would be useful to the user to understand and estimate the time necessary for the execution of jobs.

## Expected behaviour
At least for SIm4Life's based services, the progress information from iSolve should be made available to the user somehow (e.g. as a progress bar on the services's icon). If the service contains customized code, there should be a way for the user (e.g. a python function) to pass this information.

## Actual behaviour
No Info

**Comment by elisabettai** [comment] 2022-06-13 15:09
@mguidon  and @colinRawlings, do you think is still relevant?

**Comment by mguidon** [comment] 2022-06-13 15:12
Closing since this is a duplicate of another issue, and, additionally, this is no the right repository.

**Closed by mguidon** 2022-06-13 15:12 UTC
Labels: enhancement, Feedback, UI/UX
