### ISSUE TITLE
Publication linking, J-D33, Y3M2,8

### ISSUE THREAD

**Issue by KZzizzle** [ITISFoundation/osparc-issues#33] opened 2019-09-25 16:25 UTC
Ability for data, maps, and computational studies/services to be linked via meta-data to related publications and documents. These meta-data shall be displayed to users. This shall include linking publications that reference the data/maps/studies (e.g. the portal will list the publications on the landing pages). Identifying such publications should be automated (users won't need to manually input the publications that reference each dataset; automation could happen through PubMed or Google Scholar crawling
- [ ] publications and documents related to computational studies or computational services are supported in the meta-data and links are displayed

**Comment by esraneufeld** [comment] 2019-11-13 13:33
closed, because duplicate of 1067
https://github.com/ITISFoundation/osparc-simcore/issues/1067

**Closed by esraneufeld** 2019-11-13 13:33 UTC
Labels: PO issue
